export const LIST_OF_UNIVERSITIES_OPTIONS = [
  { value: "CU", label: "Cairo University" },
  { value: "AU", label: "Alexandria University" },
  { value: "AUF", label: "Ain Shams University" },
  { value: "AUC", label: "The American University in Cairo" },
  { value: "MUST", label: "Misr University for Science and Technology" },
  { value: "GUC", label: "German University in Cairo" },
  { value: "BUE", label: "The British University in Egypt" },
  { value: "ZC", label: "Zewail City of Science and Technology" },
  { value: "SU", label: "Suez Canal University" },
  { value: "UoF", label: "University of Fayoum" },
  { value: "TU", label: "Tanta University" },
  { value: "MU", label: "Mansoura University" },
  { value: "HU", label: "Helwan University" },
  { value: "BU", label: "Benha University" },
  { value: "SCU", label: "Sohag University" },
  { value: "AsyU", label: "Asyut University" },
  { value: "SUZ", label: "South Valley University" },
  { value: "KFU", label: "Kafrelsheikh University" },
  { value: "PUA", label: "Pharos University in Alexandria" },
  { value: "AASTMT", label: "Arab Academy for Science, Technology & Maritime Transport" },
  { value: "ACU", label: "Ahram Canadian University" },
  { value: "AIU", label: "Al-Azhar University" },
  { value: "CIU", label: "Canadian International College" },
  { value: "FTU", label: "Future University in Egypt" },
  { value: "KUC", label: "King Marriott Academy" },
  { value: "MISR", label: "Misr International University" },
  { value: "MNSU", label: "Minia University" },
  { value: "MTI", label: "Modern University for Technology and Information" },
  { value: "NUB", label: "Nile University" },
  { value: "NWI", label: "October 6 University" },
  { value: "PHT", label: "Pharos University in Alexandria" },
  { value: "UFE", label: "University of France in Egypt" },
];

export const LIST_OF_FACULTIES_OPTIONS = [
  { value: "ENG", label: "Faculty of Engineering" },
  { value: "MED", label: "Faculty of Medicine" },
  { value: "SCI", label: "Faculty of Science" },
  { value: "LAW", label: "Faculty of Law" },
  { value: "ART", label: "Faculty of Arts" },
  { value: "COM", label: "Faculty of Commerce" },
  { value: "PHAR", label: "Faculty of Pharmacy" },
  { value: "DEN", label: "Faculty of Dentistry" },
  { value: "AGR", label: "Faculty of Agriculture" },
  { value: "EDU", label: "Faculty of Education" },
  { value: "VET", label: "Faculty of Veterinary Medicine" },
  { value: "NUR", label: "Faculty of Nursing" },
  { value: "PHYS", label: "Faculty of Physical Therapy" },
  { value: "CIS", label: "Faculty of Computer and Information Sciences" },
  { value: "ECON", label: "Faculty of Economics and Political Science" },
  { value: "ARCH", label: "Faculty of Architecture" },
  { value: "FINE", label: "Faculty of Fine Arts" },
  { value: "LANG", label: "Faculty of Languages" },
  { value: "SOC", label: "Faculty of Social Work" },
  { value: "TOUR", label: "Faculty of Tourism and Hotels" },
  { value: "ENV", label: "Faculty of Environmental Studies" },
  { value: "SPORT", label: "Faculty of Physical Education" },
  { value: "DENT", label: "Faculty of Dentistry" },
  { value: "LL", label: "Faculty of Law and Legislation" },
  { value: "IND", label: "Faculty of Industrial Education" },
  { value: "SPEC", label: "Faculty of Specific Education" },
  { value: "THEO", label: "Faculty of Theology" },
  { value: "SHARIA", label: "Faculty of Sharia and Law" },
];

export const LIST_OF_LEVELS_OPTIONS = [
  { value: "1", label: "1st Year" },
  { value: "2", label: "2nd Year" },
  { value: "3", label: "3rd Year" },
  { value: "4", label: "4th Year" },
  { value: "5", label: "5th Year" },
  { value: "6", label: "6th Year" },
  { value: "7", label: "7th Year" },
];
